# Generated by Django 5.2.7 on 2025-11-20 14:12

import django.db.models.deletion
import G_Jobs.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(default=G_Jobs.jobs.models.generate_job_id, max_length=8, primary_key=True, serialize=False)),
                ('applicantName', models.CharField(max_length=200, verbose_name='Nombre del candidato')),
                ('applicantEmail', models.EmailField(max_length=254, verbose_name='Email del candidato')),
                ('applicantPhone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('applicantWhatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('screeningAnswers', models.JSONField(blank=True, default=dict, verbose_name='Respuestas a preguntas')),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('reviewing', 'En revisión'), ('shortlisted', 'Preseleccionada'), ('rejected', 'Rechazada'), ('accepted', 'Aceptada'), ('withdrawn', 'Retirada')], default='received', max_length=20, verbose_name='Estado')),
                ('recruiterNotes', models.TextField(blank=True, verbose_name='Notas del reclutador')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aplicación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.job', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['-createdAt'],
                'unique_together': {('job', 'applicantEmail')},
            },
        ),
    ]
