# Generated by Django 5.2.7 on 2025-11-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0003_application'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='profiles.companyprofile', verbose_name='Perfil de Empresa'),
        ),
    ]
