# Generated by Django 5.2.7 on 2025-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0004_job_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selectedPlan',
            field=models.CharField(choices=[('escencial', 'Plan Escencial (35 Bs)'), ('purpura', 'Plan Púrpura (79 Bs)'), ('impulso', 'Plan Impulso Pro (169 Bs)')], default='escencial', max_length=20, verbose_name='Plan seleccionado'),
        ),
    ]
