# Generated by Django 5.2.7 on 2025-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0005_alter_job_selectedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='municipality',
            field=models.CharField(blank=True, max_length=200, verbose_name='Provincia / Municipio'),
        ),
    ]
