# Generated by Django 5.2.7 on 2025-11-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0006_add_municipality_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='softSkills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Habilidades blandas'),
        ),
    ]
