# Generated by Django 5.2.7 on 2025-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_softskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto (ApplicationConfig)'),
        ),
        migrations.AddField(
            model_name='job',
            name='contactWhatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp (ApplicationConfig)'),
        ),
        migrations.AddField(
            model_name='job',
            name='cvSubmissionMethods',
            field=models.JSONField(blank=True, default=list, help_text='Opciones: email, form, link, whatsapp', verbose_name='Métodos de envío de CV'),
        ),
    ]
