# Generated by Django 5.2.7 on 2025-11-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0008_job_contactemail_job_contactwhatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contactEmail',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contactWhatsapp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cvSubmissionMethods',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(verbose_name='Requisitos y Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='job',
            name='softSkills',
            field=models.TextField(blank=True, verbose_name='Competencias blandas'),
        ),
        migrations.AlterField(
            model_name='job',
            name='technicalSkills',
            field=models.TextField(blank=True, verbose_name='Competencias técnicas'),
        ),
    ]
