# Generated by Django 5.2.7 on 2025-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_contactemail_remove_job_contactwhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='billingBusinessName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='job',
            name='billingInvoiceEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email para factura digital'),
        ),
        migrations.AddField(
            model_name='job',
            name='billingNIT',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIT'),
        ),
    ]
