# Generated by Django 5.2.7 on 2025-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_billing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='job',
            name='softSkills',
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Formación requerida'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=200, verbose_name='Experiencia necesaria'),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Idiomas requeridos'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Responsabilidades'),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='job',
            name='billingBusinessName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='job',
            name='billingInvoiceEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para factura'),
        ),
        migrations.AlterField(
            model_name='job',
            name='billingNIT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='technicalSkills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Habilidades técnicas'),
        ),
    ]
