# Generated by Django 5.2.7 on 2025-11-26 21:34

from django.db import migrations
from datetime import timedelta


def recalculate_expiry_dates(apps, schema_editor):
    """Recalcular fechas de vencimiento basándose en createdAt + duración del plan"""
    Job = apps.get_model('G_Jobs.jobs', 'Job')

    # Duración de cada plan en días
    plan_durations = {
        'escencial': 15,
        'purpura': 30,
        'impulso': 30,
        # Incluir variantes por si acaso
        'basico': 15,
        'professional': 30,
        'premium': 30,
    }

    # Recalcular todos los jobs
    for job in Job.objects.all():
        plan = job.selectedPlan or 'escencial'
        duration = plan_durations.get(plan, 15)

        # Calcular nueva fecha de vencimiento basándose en createdAt
        new_expiry = (job.createdAt.date() + timedelta(days=duration))
        job.expiryDate = new_expiry
        job.save(update_fields=['expiryDate'])

        print(f"[OK] {job.id}: {job.title[:30]} | Plan: {plan} | Nueva vigencia: {new_expiry}")


def reverse_recalculate(apps, schema_editor):
    """No se puede revertir, esta es una migración de datos crítica"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0014_alter_job_whatsapp'),
    ]

    operations = [
        migrations.RunPython(recalculate_expiry_dates, reverse_recalculate),
    ]
