# Generated by Django 5.2.7 on 2025-11-27 15:01

import django.db.models.deletion
import G_Jobs.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_recalculate_expiry_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAuditLog',
            fields=[
                ('id', models.CharField(default=G_Jobs.jobs.models.generate_job_id, max_length=8, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('activated', 'Activado'), ('deactivated', 'Desactivado'), ('duplicated', 'Duplicado'), ('deleted', 'Eliminado'), ('payment_verified', 'Pago verificado'), ('payment_rejected', 'Pago rechazado')], max_length=20, verbose_name='Acción')),
                ('userEmail', models.EmailField(blank=True, max_length=254, verbose_name='Email del usuario')),
                ('changedFields', models.JSONField(blank=True, default=dict, help_text='JSON con before/after de los campos que cambieron', verbose_name='Campos modificados')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('clientIP', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='G_Jobs.jobs.job', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Auditoría de Trabajo',
                'verbose_name_plural': 'Auditorías de Trabajos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job', '-timestamp'], name='jobs_jobaud_job_id_6682c9_idx'), models.Index(fields=['userEmail', '-timestamp'], name='jobs_jobaud_userEma_c9f29f_idx'), models.Index(fields=['action'], name='jobs_jobaud_action_bd583a_idx')],
            },
        ),
    ]
