# Generated by Django 5.2.7 on 2025-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0016_add_jobauditlog_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='job',
            name='isDeleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado (borrado lógico)'),
        ),
    ]
