# Generated by Django 5.2.7 on 2025-11-27 15:33

from django.db import migrations


def assign_company_profiles(apps, schema_editor):
    """
    Asigna el primer CompanyProfile de cada usuario a sus trabajos existentes
    que no tengan companyProfile asignado
    """
    Job = apps.get_model('G_Jobs.jobs', 'Job')
    UserProfile = apps.get_model('profiles', 'UserProfile')
    CompanyProfile = apps.get_model('profiles', 'CompanyProfile')

    # Obtener todos los trabajos sin companyProfile asignado
    jobs_without_profile = Job.objects.filter(companyProfile__isnull=True)

    print(f"\n[MIGRATION] Encontrados {jobs_without_profile.count()} trabajos sin companyProfile")

    updated_count = 0
    for job in jobs_without_profile:
        # Buscar el email del usuario en el campo email del job
        # o tratar de encontrar un usuario que haya creado este job
        # Intentamos encontrar un UserProfile que tenga un CompanyProfile
        company_profiles = CompanyProfile.objects.filter(
            owner__email__iexact=job.email
        )

        if company_profiles.exists():
            # Asignar el primer CompanyProfile encontrado
            job.companyProfile = company_profiles.first()
            job.save(update_fields=['companyProfile'])
            updated_count += 1
            print(f"[MIGRATION] Job '{job.title}' (ID: {job.id}) asignado a CompanyProfile")
        else:
            # Si no encontramos un perfil de empresa por email, intentar otro enfoque
            # Buscar por nombre de empresa
            company_profiles = CompanyProfile.objects.filter(
                companyName__iexact=job.companyName
            )

            if company_profiles.exists():
                job.companyProfile = company_profiles.first()
                job.save(update_fields=['companyProfile'])
                updated_count += 1
                print(f"[MIGRATION] Job '{job.title}' (ID: {job.id}) asignado por nombre de empresa")

    print(f"[MIGRATION] Total de trabajos actualizados: {updated_count}/{jobs_without_profile.count()}\n")


def reverse_assign_company_profiles(apps, schema_editor):
    """
    Reversa: establecer companyProfile a NULL nuevamente
    """
    Job = apps.get_model('G_Jobs.jobs', 'Job')
    Job.objects.all().update(companyProfile=None)


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0017_job_deletedat_job_isdeleted'),
    ]

    operations = [
        migrations.RunPython(assign_company_profiles, reverse_assign_company_profiles),
    ]
