# Generated by Django 5.2.7 on 2025-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_assign_company_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='planDuration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración del plan en días (capturada al publicar)'),
        ),
        migrations.AddField(
            model_name='job',
            name='planLabel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etiqueta del plan (capturada al publicar)'),
        ),
        migrations.AddField(
            model_name='job',
            name='planPrice',
            field=models.CharField(blank=True, max_length=50, verbose_name='Precio del plan (capturado al publicar)'),
        ),
    ]
