# Generated by Django 5.2.7 on 2025-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='ci_complement',
            field=models.CharField(blank=True, help_text='Complemento de la Cédula de Identidad (opcional)', max_length=5, verbose_name='Complemento CI'),
        ),
    ]
