# Generated by Django 5.2.7 on 2025-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0027_alter_job_selectedplan_alter_planorder_selected_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planorder',
            name='email',
            field=models.EmailField(blank=True, default='noreply@guiaspurpuras.com', help_text='Solo requerido si el usuario solicitó factura', max_length=254, verbose_name='Email para factura'),
        ),
    ]
