# Generated by Django 5.2.7 on 2025-12-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.jobs', '0029_remove_both_application_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked_user',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='company',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='job',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
        migrations.DeleteModel(
            name='PlanOrder',
        ),
    ]
