# Generated by Django 5.2.7 on 2025-12-26 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_alter_blockeduser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejectedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Rechazo'),
        ),
        migrations.AddField(
            model_name='job',
            name='rejectedBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por'),
        ),
        migrations.AddField(
            model_name='job',
            name='rejectionReason',
            field=models.TextField(blank=True, help_text='Razón por la cual el anuncio fue rechazado (violación de políticas, contenido inapropiado, etc.)', verbose_name='Motivo de Rechazo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('paused', 'Pausado'), ('closed', 'Cerrado'), ('draft', 'Borrador'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
