# Generated by Django 5.2.7 on 2025-12-26 02:01

import G_Jobs.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_job_rejectedat_job_rejectedby_job_rejectionreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='proofOfPayment',
            field=models.ImageField(null=True, upload_to=G_Jobs.jobs.models.payment_proof_upload_path, verbose_name='Comprobante de pago'),
        ),
    ]
