# Generated by Django 5.2.7 on 2025-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_alter_job_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicationDeadline',
            field=models.DateField(blank=True, help_text='Fecha límite en que los candidatos pueden postular. Si no se especifica, se usa expiryDate.', null=True, verbose_name='Fecha límite para postulaciones'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiryDate',
            field=models.DateField(verbose_name='Fecha de vencimiento del plan (visibilidad del anuncio)'),
        ),
    ]
