# Generated by Django 5.2.7 on 2025-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_job_applicationdeadline_alter_job_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salaryType',
            field=models.CharField(choices=[('range', 'Rango'), ('fixed', 'Fijo'), ('negotiable', 'A convenir'), ('pretension_salarial', 'Pretensión Salarial')], default='negotiable', max_length=20, verbose_name='Tipo de salario'),
        ),
    ]
