# Generated by Django 5.2.7 on 2026-01-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_add_pretension_salarial_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicationInstructions',
            field=models.TextField(blank=True, help_text='Instrucciones especiales para candidatos que aplican externamente', verbose_name='Instrucciones de aplicación'),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.URLField(blank=True, help_text='URL del sitio web de la empresa', max_length=500, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp o teléfono para contacto', max_length=50, verbose_name='WhatsApp/Teléfono'),
        ),
    ]
