# Generated by Django 5.2.7 on 2026-01-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_add_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Enlace de WhatsApp (generado automáticamente desde número)', max_length=500, verbose_name='WhatsApp'),
        ),
    ]
