# Generated by Django 5.2.7 on 2025-12-15 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0030_alter_blockeduser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('ci', models.CharField(blank=True, max_length=20, verbose_name='CI')),
                ('ci_complement', models.CharField(blank=True, max_length=5, verbose_name='Complemento CI')),
                ('email', models.EmailField(blank=True, default='noreply@guiaspurpuras.com', help_text='Solo requerido si el usuario solicitó factura', max_length=254, verbose_name='Email para factura')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('selected_plan', models.CharField(choices=[('estandar', 'Estándar'), ('purpura', 'Púrpura'), ('impulso', 'Impulso Pro')], default='estandar', max_length=50, verbose_name='Plan seleccionado')),
                ('plan_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del plan')),
                ('status', models.CharField(choices=[('processing', 'En Proceso'), ('completed', 'Completado')], default='processing', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_order', to='jobs.job', verbose_name='Trabajo asociado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden de Plan',
                'verbose_name_plural': 'Órdenes de Planes',
                'db_table': 'jobs_planorder',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='jobs_planor_created_1c4b9a_idx'), models.Index(fields=['user'], name='jobs_planor_user_id_df8a6b_idx'), models.Index(fields=['status'], name='jobs_planor_status_5aa25d_idx')],
            },
        ),
    ]
