# Generated by Django 5.2.7 on 2025-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_companyprofile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto Público'),
        ),
    ]
