"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9f5hdn7p+ajd$hgjnjr7!u&04&y839j!f35@9_*!upjvmo_*#='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Jazzmin (debe ir PRIMERO antes de django.contrib.admin)
    'jazzmin',

    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CORS
    'corsheaders',

    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # Apps compartidas
    'auth_api',
    'profiles',

    # G_Jobs - Guías de Trabajos
    'G_Jobs.jobs',  # Core de trabajos
    'G_Jobs.catalogs',  # Catálogos dinámicos (JobCategory, ContractType, City)
    'G_Jobs.payments',  # Pagos y facturación (PlanOrder)
    'G_Jobs.moderation',  # Moderación de usuarios (BlockedUser)
    'G_Jobs.dashboard',  # Dashboard y estadísticas de usuario
    'G_Jobs.plans',  # Planes de publicación
    'G_Jobs.reports',  # Sistema de reportes diarios
    'G_Jobs.audit',  # Sistema de auditoría
    'G_Jobs.applicants',  # Sistema de postulantes y aplicaciones
    'G_Jobs.notifications',  # Sistema de notificaciones
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'G_Jobs.audit.middleware.AuditMiddleware',  # Middleware de auditoría
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'auth_api.CustomUser'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Debug: Print incoming origins
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    # ===== TIEMPOS DE EXPIRACIÓN (Mejores Prácticas de Seguridad) =====
    # Access Token: 15 minutos (corto por seguridad, se refresca automáticamente)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # Refresh Token: 1 día (sesión válida por 24 horas)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # ===== ROTACIÓN Y BLACKLIST (Seguridad Mejorada) =====
    # Rotar refresh token en cada uso (previene reutilización de tokens robados)
    'ROTATE_REFRESH_TOKENS': True,
    # Agregar tokens viejos al blacklist después de rotación
    'BLACKLIST_AFTER_ROTATION': True,
    # Actualizar last_login del usuario
    'UPDATE_LAST_LOGIN': True,

    # ===== CONFIGURACIÓN DE FIRMA =====
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_IN_BLACKLIST_CLAIM': 'jti',

    # ===== TOKENS DESLIZANTES =====
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# ============================================================================
# JAZZMIN CONFIGURATION - Admin Dashboard Professional
# ============================================================================

JAZZMIN_SETTINGS = {
    # ========== BRANDING ==========
    "site_title": "Guías Púrpuras Admin",
    "site_header": "Guías Púrpuras",
    "site_brand": "Guías Púrpuras",
    "site_logo": "admin/img/logo.ico",  # Logo en el sidebar
    "login_logo": "admin/img/logo.ico",  # Logo en página de login
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "admin/img/logo.ico",  # Favicon
    "welcome_sign": "Bienvenido al Panel Administrativo",
    "copyright": "Guías Púrpuras - Bolivia",

    # ========== SEARCH ==========
    "search_model": ["auth_api.CustomUser", "jobs.Job", "profiles.CompanyProfile", "applicants.JobApplication", "applicants.ApplicantCV"],

    # ========== USER MENU ==========
    "user_avatar": None,

    # ========== TOP MENU LINKS ==========
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        # URL del sitio frontend - DESARROLLO: localhost:5173
        # PRODUCCIÓN: Cambiar a "https://guiaspurpuras.com.bo" cuando se despliegue
        {"name": "Ver Sitio", "url": "http://localhost:5173/", "new_window": True},
        # {"name": "Ver Sitio", "url": "https://guiaspurpuras.com.bo", "new_window": True},  # PRODUCCIÓN
        {"app": "jobs"},
    ],

    # ========== SIDE MENU (MENÚ LATERAL CON JERARQUÍA) ==========
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "icons": {
        # ===== DJANGO ADMIN CORE =====
        "admin": "fas fa-cogs",
        "admin.LogEntry": "fas fa-clipboard-list",  # Registros de auditoría
        "auth": "fas fa-lock",
        "auth.Group": "fas fa-users-cog",
        "auth.Permission": "fas fa-key",
        "contenttypes": "fas fa-puzzle-piece",
        "contenttypes.ContentType": "fas fa-cubes",
        "sessions": "fas fa-clock",
        "sessions.Session": "fas fa-user-clock",

        # ===== G_JOBS - GUÍAS DE TRABAJOS =====
        "jobs": "fas fa-briefcase",
        "jobs.Job": "fas fa-file-alt",

        # ===== CATÁLOGOS DINÁMICOS =====
        "catalogs": "fas fa-database",
        "catalogs.JobCategory": "fas fa-tags",
        "catalogs.ContractType": "fas fa-file-contract",
        "catalogs.City": "fas fa-map-marker-alt",

        # ===== PAGOS Y FACTURACIÓN =====
        "payments": "fas fa-credit-card",
        "payments.PlanOrder": "fas fa-receipt",

        # ===== MODERACIÓN =====
        "moderation": "fas fa-user-shield",
        "moderation.BlockedUser": "fas fa-user-slash",

        # ===== PLANES =====
        "plans": "fas fa-gem",
        "plans.Plan": "fas fa-crown",

        # ===== REPORTES =====
        "reports": "fas fa-chart-bar",
        "reports.DailyReport": "fas fa-calendar-day",

        # ===== PERFILES =====
        "profiles": "fas fa-users",
        "profiles.CompanyProfile": "fas fa-building",
        "profiles.UserProfile": "fas fa-user-circle",

        # ===== AUDITORÍA =====
        "audit": "fas fa-shield-alt",
        "audit.AuditLog": "fas fa-history",
        "audit.AuditLogSummary": "fas fa-clipboard-check",

        # ===== NOTIFICACIONES =====
        "notifications": "fas fa-bell",
        "notifications.Notification": "fas fa-envelope",

        # ===== POSTULANTES Y APLICACIONES =====
        "applicants": "fas fa-user-friends",
        "applicants.ApplicantProfile": "fas fa-id-card",
        "applicants.ApplicantCV": "fas fa-file-pdf",
        "applicants.JobApplication": "fas fa-paper-plane",
        "applicants.SavedJob": "fas fa-bookmark",

        # ===== AUTENTICACIÓN =====
        "auth_api": "fas fa-user-shield",
        "auth_api.CustomUser": "fas fa-user-tie",
        "auth_api.AdminUser": "fas fa-user-secret",

        # ===== TOKEN BLACKLIST =====
        "token_blacklist": "fas fa-ban",
        "token_blacklist.OutstandingToken": "fas fa-key",
        "token_blacklist.BlacklistedToken": "fas fa-times-circle",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ========== RELATED MODAL (Para selección de relaciones) ==========
    "related_modal_active": False,

    # ========== UI CUSTOMIZATION ==========
    "custom_css": None,  # Sin CSS personalizado - usar estilos por defecto
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # ========== CHANGE FORM TEMPLATES ==========
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth_api.CustomUser": "collapsible",
        "jobs.Job": "horizontal_tabs",
    },

    # ========== LANGUAGE CHOOSER ==========
    "language_chooser": False,
}

# ============================================================================
# JAZZMIN UI TWEAKS - Personalización Visual
# ============================================================================

JAZZMIN_UI_TWEAKS = {
    # ===== TEMA GENERAL =====
    "theme": "pulse",  # Tema Pulse - Bootstrap theme

    # ===== NAVBAR (Barra superior) =====
    "navbar": "navbar-dark",  # Navbar oscuro por defecto
    "navbar_fixed": True,

    # ===== SIDEBAR (Barra lateral) =====
    "sidebar": "sidebar-dark-primary",  # Sidebar negro por defecto
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # ===== ACCENTS (Acentos de color) =====
    "accent": "accent-primary",  # Acento primario por defecto

    # ===== BRAND (Logo y marca) =====
    "brand_small_text": False,
    "brand_colour": "navbar-dark",

    # ===== FOOTER =====
    "footer_fixed": False,

    # ===== BODY =====
    "body_small_text": False,

    # ===== ACTIONS (Botones de acción) =====
    "actions_sticky_top": True,
}


# ============================================================================
# EMAIL CONFIGURATION - Sistema de Recuperación de Contraseña
# ============================================================================

import os

# ========== DESARROLLO (LOCALHOST) ==========
# En localhost, los emails se muestran en la consola del servidor (terminal)
# Esto es perfecto para desarrollo y testing
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@guiaspurpuras.com'
    print("[EMAIL] Modo desarrollo - Emails se mostraran en consola")

# ========== PRODUCCIÓN (RENDER) ==========
# En producción necesitarás configurar variables de entorno en Render
# Ve a tu dashboard de Render → Settings → Environment Variables
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    # ⚠️ IMPORTANTE: Configurar estas variables de entorno en Render:
    #
    # 1. EMAIL_HOST - Ejemplo para Gmail: 'smtp.gmail.com'
    # 2. EMAIL_PORT - Puerto SMTP (587 para TLS, 465 para SSL)
    # 3. EMAIL_HOST_USER - Tu email completo (ejemplo: tuempresa@gmail.com)
    # 4. EMAIL_HOST_PASSWORD - App password de Gmail o contraseña del servicio
    # 5. DEFAULT_FROM_EMAIL - Email que aparecerá como remitente
    # 6. FRONTEND_URL - URL de tu frontend en producción (ejemplo: https://tuapp.vercel.app)
    #
    # Para Gmail:
    # - Ve a https://myaccount.google.com/security
    # - Habilita "Verificación en 2 pasos"
    # - Luego ve a "Contraseñas de aplicaciones"
    # - Genera una contraseña para "Correo" y úsala en EMAIL_HOST_PASSWORD
    #
    # Alternativas a Gmail:
    # - SendGrid (https://sendgrid.com) - 100 emails gratis/día
    # - Mailgun (https://www.mailgun.com) - 5,000 emails gratis/mes
    # - AWS SES (https://aws.amazon.com/ses/) - Muy económico

    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@guiaspurpuras.com')

    # URL del frontend en producción (para los enlaces de recuperación)
    FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://tuapp.vercel.app')

    print(f"[EMAIL] Modo produccion - Usando {EMAIL_HOST}:{EMAIL_PORT}")

# Email para desarrollo local (siempre se configura)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@guiaspurpuras.com')

