"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9f5hdn7p+ajd$hgjnjr7!u&04&y839j!f35@9_*!upjvmo_*#='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Jazzmin (debe ir PRIMERO antes de django.contrib.admin)
    'jazzmin',

    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CORS
    'corsheaders',

    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # Apps compartidas
    'auth_api',
    'profiles',
    'audit',  # Sistema de auditoría

    # G_Jobs - Guías de Trabajos
    'G_Jobs.jobs',  # Core de trabajos
    'G_Jobs.catalogs',  # Catálogos dinámicos (JobCategory, ContractType, City)
    'G_Jobs.payments',  # Pagos y facturación (PlanOrder)
    'G_Jobs.moderation',  # Moderación de usuarios (BlockedUser)
    'G_Jobs.dashboard',  # Dashboard y estadísticas de usuario
    'G_Jobs.plans',  # Planes de publicación
    'G_Jobs.reports',  # Sistema de reportes diarios
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',  # Middleware de auditoría
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'auth_api.CustomUser'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Debug: Print incoming origins
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_IN_BLACKLIST_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# ============================================================================
# JAZZMIN CONFIGURATION - Admin Dashboard Professional
# ============================================================================

JAZZMIN_SETTINGS = {
    # ========== BRANDING ==========
    "site_title": "Guías Púrpuras Admin",
    "site_header": "Guías Púrpuras",
    "site_brand": "Guías Púrpuras",
    "site_logo": "admin/img/logo.ico",  # Logo en el sidebar
    "login_logo": "admin/img/logo.ico",  # Logo en página de login
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "admin/img/logo.ico",  # Favicon
    "welcome_sign": "Bienvenido al Panel Administrativo",
    "copyright": "Guías Púrpuras - Bolivia",

    # ========== SEARCH ==========
    "search_model": ["auth_api.CustomUser", "jobs.Job", "profiles.CompanyProfile"],

    # ========== USER MENU ==========
    "user_avatar": None,

    # ========== TOP MENU LINKS ==========
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Sitio", "url": "/", "new_window": True},
        {"name": "Soporte", "url": "https://github.com/anthropics/claude-code/issues", "new_window": True},
        {"model": "auth_api.CustomUser"},
        {"app": "jobs"},
    ],

    # ========== SIDE MENU (MENÚ LATERAL CON JERARQUÍA) ==========
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "icons": {
        # ===== G_JOBS - GUÍAS DE TRABAJOS =====
        "G_Jobs.jobs": "fas fa-briefcase",
        "G_Jobs.jobs.Job": "fas fa-file-alt",

        # ===== CATÁLOGOS DINÁMICOS =====
        "G_Jobs.catalogs": "fas fa-database",
        "G_Jobs.catalogs.JobCategory": "fas fa-tags",
        "G_Jobs.catalogs.ContractType": "fas fa-file-contract",
        "G_Jobs.catalogs.City": "fas fa-map-marker-alt",

        # ===== PAGOS Y FACTURACIÓN =====
        "G_Jobs.payments": "fas fa-credit-card",
        "G_Jobs.payments.PlanOrder": "fas fa-receipt",

        # ===== MODERACIÓN =====
        "G_Jobs.moderation": "fas fa-user-shield",
        "G_Jobs.moderation.BlockedUser": "fas fa-user-slash",

        # ===== DASHBOARD =====
        "G_Jobs.dashboard": "fas fa-chart-line",

        # ===== PLANES =====
        "G_Jobs.plans": "fas fa-gem",
        "G_Jobs.plans.Plan": "fas fa-crown",

        # ===== REPORTES =====
        "G_Jobs.reports": "fas fa-chart-bar",
        "G_Jobs.reports.DailyReport": "fas fa-calendar-day",

        # ===== PERFILES =====
        "profiles": "fas fa-users",
        "profiles.CompanyProfile": "fas fa-building",
        "profiles.UserProfile": "fas fa-user-circle",

        # ===== REPORTES =====
        "reports": "fas fa-chart-line",
        "reports.DailyReport": "fas fa-calendar-day",

        # ===== AUDITORÍA =====
        "audit": "fas fa-shield-alt",
        "audit.AuditLog": "fas fa-history",
        "audit.AuditLogSummary": "fas fa-clipboard-list",

        # ===== AUTENTICACIÓN =====
        "auth": "fas fa-lock",
        "auth.Group": "fas fa-users-cog",
        "auth_api": "fas fa-user-shield",
        "auth_api.CustomUser": "fas fa-user-tie",

        # ===== TOKEN BLACKLIST =====
        "token_blacklist": "fas fa-ban",
        "token_blacklist.OutstandingToken": "fas fa-key",
        "token_blacklist.BlacklistedToken": "fas fa-times-circle",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ========== RELATED MODAL (Para selección de relaciones) ==========
    "related_modal_active": False,

    # ========== UI CUSTOMIZATION ==========
    "custom_css": None,  # Sin CSS personalizado - usar estilos por defecto
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # ========== CHANGE FORM TEMPLATES ==========
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth_api.CustomUser": "collapsible",
        "jobs.Job": "horizontal_tabs",
    },

    # ========== LANGUAGE CHOOSER ==========
    "language_chooser": False,
}

# ============================================================================
# JAZZMIN UI TWEAKS - Personalización Visual
# ============================================================================

JAZZMIN_UI_TWEAKS = {
    # ===== TEMA GENERAL =====
    "theme": "flatly",  # Tema por defecto Jazzmin

    # ===== NAVBAR (Barra superior) =====
    "navbar": "navbar-dark",  # Navbar oscuro por defecto
    "navbar_fixed": True,

    # ===== SIDEBAR (Barra lateral) =====
    "sidebar": "sidebar-dark-primary",  # Sidebar negro por defecto
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # ===== ACCENTS (Acentos de color) =====
    "accent": "accent-primary",  # Acento primario por defecto

    # ===== BRAND (Logo y marca) =====
    "brand_small_text": False,
    "brand_colour": "navbar-dark",

    # ===== FOOTER =====
    "footer_fixed": False,

    # ===== BODY =====
    "body_small_text": False,

    # ===== ACTIONS (Botones de acción) =====
    "actions_sticky_top": True,
}

