# Generated by Django 5.2.7 on 2025-11-20 13:31

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=jobs.models.generate_job_id, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('companyName', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('companyAnonymous', models.BooleanField(default=False, verbose_name='Publicar de forma anónima')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('jobCategory', models.CharField(max_length=100, verbose_name='Categoría')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Subcategoría')),
                ('contractType', models.CharField(max_length=100, verbose_name='Tipo de contrato')),
                ('expiryDate', models.DateField(verbose_name='Fecha de vencimiento')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsabilidades')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Formación requerida')),
                ('experience', models.CharField(blank=True, max_length=200, verbose_name='Experiencia necesaria')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Idiomas requeridos')),
                ('technicalSkills', models.CharField(blank=True, max_length=500, verbose_name='Habilidades técnicas')),
                ('salaryType', models.CharField(choices=[('range', 'Rango salarial'), ('fixed', 'Salario fijo'), ('negotiable', 'A convenir'), ('hidden', 'No mostrar')], default='range', max_length=20, verbose_name='Tipo de salario')),
                ('salaryMin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaryMax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaryFixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficios adicionales')),
                ('vacancies', models.IntegerField(default=1, verbose_name='Número de vacantes')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('applicationInstructions', models.TextField(blank=True, verbose_name='Instrucciones de aplicación')),
                ('applicationType', models.CharField(choices=[('internal', 'Interna'), ('external', 'Externa'), ('both', 'Ambas')], default='internal', max_length=20, verbose_name='Tipo de aplicación')),
                ('externalApplicationUrl', models.URLField(blank=True, verbose_name='URL de aplicación externa')),
                ('selectedPlan', models.CharField(choices=[('free', 'Gratis'), ('featured', 'Destacado'), ('top', 'TOP')], default='free', max_length=20, verbose_name='Plan seleccionado')),
                ('screeningQuestions', models.JSONField(blank=True, default=list, verbose_name='Preguntas de filtrado')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('applications', models.IntegerField(default=0, verbose_name='Aplicaciones')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada'), ('draft', 'Borrador')], default='active', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Oferta de Trabajo',
                'verbose_name_plural': 'Ofertas de Trabajo',
                'ordering': ['-createdAt'],
            },
        ),
    ]
