# Generated by Django 5.2.7 on 2025-11-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia/Municipio'),
        ),
        migrations.AddField(
            model_name='job',
            name='softSkills',
            field=models.CharField(blank=True, max_length=500, verbose_name='Habilidades blandas'),
        ),
    ]
