# Generated by Django 5.2.7 on 2025-11-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_planduration_job_planlabel_job_planprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='education',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='softSkills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='technicalSkills',
        ),
    ]
