# Generated by Django 5.2.7 on 2025-12-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_job_paymentverifiedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Verificación'), ('active', 'Activa'), ('closed', 'Cerrada'), ('draft', 'Borrador')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
