# Generated by Django 5.2.7 on 2025-12-03 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_planorder_ci_complement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la ciudad')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('region', models.CharField(blank=True, choices=[('altiplano', 'Altiplano'), ('valles', 'Valles'), ('llanos', 'Llanos')], max_length=50, verbose_name='Región')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de contrato')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono (Material Icons)', max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Trabajo',
                'verbose_name_plural': 'Categorías de Trabajo',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobauditlog',
            name='job',
        ),
        migrations.AlterModelOptions(
            name='planorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de Plan', 'verbose_name_plural': 'Órdenes de Planes'},
        ),
        migrations.RemoveIndex(
            model_name='planorder',
            name='jobs_planor_user_id_c84a65_idx',
        ),
        migrations.RemoveIndex(
            model_name='planorder',
            name='jobs_planor_invoice_75b927_idx',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='is_permanent',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='reason_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applicationInstructions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='billingBusinessName',
        ),
        migrations.RemoveField(
            model_name='job',
            name='billingInvoiceEmail',
        ),
        migrations.RemoveField(
            model_name='job',
            name='billingNIT',
        ),
        migrations.RemoveField(
            model_name='job',
            name='planDuration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='planLabel',
        ),
        migrations.RemoveField(
            model_name='job',
            name='planPrice',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.RemoveField(
            model_name='job',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='company_data',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='electronic_invoice_email',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='electronic_invoice_sent_date',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='electronic_invoice_whatsapp',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='planorder',
            name='plan',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='job',
            name='publishDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='email',
            field=models.EmailField(default='noreply@guiaspurpuras.com', max_length=254, verbose_name='Email para factura'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_order', to='jobs.job', verbose_name='Trabajo asociado'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio del plan'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='selected_plan',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('destacado', 'Destacado'), ('purpura', 'Púrpura')], default='gratuito', max_length=50, verbose_name='Plan seleccionado'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bloqueado el'),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked_user',
            field=models.ForeignKey(limit_choices_to={'role': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_companies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario bloqueado'),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='company',
            field=models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_blocked_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Comportamiento inapropiado'), ('unqualified', 'No calificado repetidamente'), ('other', 'Otra razón')], max_length=50, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applicationType',
            field=models.CharField(choices=[('internal', 'Interna (en Guías Púrpuras)'), ('external', 'Externa (URL propia)'), ('both', 'Ambas')], default='internal', max_length=20, verbose_name='Tipo de aplicación'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applications',
            field=models.IntegerField(default=0, verbose_name='Número de aplicaciones'),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email del publicador'),
        ),
        migrations.AlterField(
            model_name='job',
            name='externalApplicationUrl',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL externa de aplicación'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryFixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario fijo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryMax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario máximo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryMin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mínimo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryType',
            field=models.CharField(choices=[('range', 'Rango'), ('fixed', 'Fijo'), ('negotiable', 'A convenir')], default='negotiable', max_length=20, verbose_name='Tipo de salario'),
        ),
        migrations.AlterField(
            model_name='job',
            name='selectedPlan',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('destacado', 'Destacado'), ('purpura', 'Púrpura')], default='gratuito', max_length=50, verbose_name='Plan seleccionado'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('paused', 'Pausado'), ('closed', 'Cerrado'), ('draft', 'Borrador')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='job',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Número de vistas'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='ci',
            field=models.CharField(blank=True, max_length=20, verbose_name='CI'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='ci_complement',
            field=models.CharField(blank=True, max_length=5, verbose_name='Complemento CI'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='nit',
            field=models.CharField(max_length=50, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='status',
            field=models.CharField(choices=[('processing', 'En Proceso'), ('completed', 'Completado')], default='processing', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='planorder',
            index=models.Index(fields=['-created_at'], name='jobs_planor_created_1c4b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='planorder',
            index=models.Index(fields=['user'], name='jobs_planor_user_id_df8a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='jobs_city_slug_32b22c_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active', 'order'], name='jobs_city_is_acti_75d27e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region'], name='jobs_city_region_6d31a3_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['slug'], name='jobs_contra_slug_b0063c_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['is_active', 'order'], name='jobs_contra_is_acti_0f056e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['slug'], name='jobs_jobcat_slug_3b5636_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['is_active', 'order'], name='jobs_jobcat_is_acti_d56492_idx'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='JobAuditLog',
        ),
    ]
