# Generated by Django 5.2.7 on 2026-01-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre de la empresa que publicó el anuncio', max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AddField(
            model_name='planorder',
            name='job_title',
            field=models.CharField(blank=True, help_text='Título del trabajo asociado a esta orden', max_length=300, verbose_name='Título del Anuncio'),
        ),
    ]
