# Generated by Django 5.2.7 on 2025-11-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('escencial', 'Escencial'), ('purpura', 'Púrpura'), ('impulso', 'Impulso Pro')], help_text='Nombre único del plan', max_length=50, unique=True)),
                ('label', models.CharField(help_text="Etiqueta para mostrar en UI (ej: 'Escencial (35 Bs)')", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción del plan para el usuario')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en Bs', max_digits=10)),
                ('currency', models.CharField(default='Bs', help_text='Moneda (Bs, $, etc)', max_length=3)),
                ('duration_days', models.IntegerField(default=15, help_text='Duración del anuncio en días')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Características y límites del plan en formato JSON')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está disponible este plan?')),
                ('order', models.IntegerField(default=0, help_text='Orden para mostrar en la UI (menor número = primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
