# Generated by Django 5.2.7 on 2025-11-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_populate_plan_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='application_form',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='has_premium_badge',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='has_social_media_share',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_editions',
        ),
    ]
