# Generated by Django 5.2.7 on 2025-12-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_badge_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='applicant_management',
            field=models.BooleanField(default=True, help_text='¿Incluye gestión de postulantes?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='applicant_management_text',
            field=models.CharField(blank=True, default='Si incluye', help_text="Texto a mostrar en tabla de comparación (ej: 'Si incluye', 'Hasta 50 candidatos')", max_length=200),
        ),
    ]
