# Generated by Django 5.2.7 on 2025-12-29 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='applications_received',
            field=models.IntegerField(default=0, verbose_name='Aplicaciones Recibidas'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='jobs_closed_today',
            field=models.IntegerField(default=0, verbose_name='Trabajos Cerrados Hoy'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='views_today',
            field=models.IntegerField(default=0, verbose_name='Vistas del Día'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='active_jobs',
            field=models.IntegerField(default=0, verbose_name='Trabajos Activos (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='closed_jobs',
            field=models.IntegerField(default=0, verbose_name='Trabajos Cerrados (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_active_users',
            field=models.IntegerField(default=0, verbose_name='Usuarios Activos (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='Vistas Totales (Snapshot)'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Tipo de Reporte')),
                ('period_start', models.DateField(verbose_name='Inicio del Período')),
                ('period_end', models.DateField(verbose_name='Fin del Período')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/%Y/%m/', verbose_name='Archivo PDF')),
                ('metrics', models.JSONField(default=dict, help_text='JSON con todas las métricas del período', verbose_name='Métricas Calculadas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('error_message', models.TextField(blank=True, help_text='Si falló, guardar el error aquí', verbose_name='Mensaje de Error')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte PDF',
                'verbose_name_plural': 'Reportes PDF',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='reports_rep_generat_fa1e6b_idx'), models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx')],
            },
        ),
    ]
