# Generated by Django 5.2.7 on 2025-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_applications_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal (Lun-Dom)'), ('last_7_days', 'Últimos 7 Días'), ('monthly', 'Mensual')], max_length=20, verbose_name='Tipo de Reporte'),
        ),
    ]
