# Generated by Django 5.2.7 on 2025-12-01 20:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador del Sistema',
                'verbose_name_plural': 'Administradores del Sistema',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_api.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
