# Generated by Django 5.2.7 on 2025-12-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación de Contraseña',
                'verbose_name_plural': 'Tokens de Recuperación de Contraseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
