# Generated by Django 5.2.7 on 2025-12-29 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_application', 'Nueva postulación recibida'), ('payment_verified', 'Pago verificado'), ('payment_rejected', 'Pago rechazado'), ('job_expiring_soon', 'Anuncio próximo a vencer'), ('job_expired', 'Anuncio vencido'), ('application_sent', 'Postulación enviada'), ('saved_job_closed', 'Trabajo guardado cerrado'), ('blocked_attempt', 'Intento de postulación bloqueado'), ('password_changed', 'Contraseña cambiada'), ('profile_updated', 'Perfil actualizado'), ('system', 'Notificación del sistema')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'jobs_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='jobs_notifi_user_id_9726a1_idx'), models.Index(fields=['user', 'is_read'], name='jobs_notifi_user_id_c6ad4a_idx')],
            },
        ),
    ]
