# Generated by Django 5.2.7 on 2025-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Descartada el'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='Descartada'),
        ),
    ]
