# Generated by Django 5.2.7 on 2026-01-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_dismissed_at_notification_is_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_application', 'Nueva postulación recibida'), ('payment_verified', 'Pago verificado'), ('payment_rejected', 'Pago rechazado'), ('invoice_created', 'Orden de facturación creada'), ('invoice_completed', 'Facturación completada'), ('job_expiring_soon', 'Anuncio próximo a vencer'), ('job_expired', 'Anuncio vencido'), ('application_sent', 'Postulación enviada'), ('saved_job_closed', 'Trabajo guardado cerrado'), ('blocked_attempt', 'Intento de postulación bloqueado'), ('password_changed', 'Contraseña cambiada'), ('profile_updated', 'Perfil actualizado'), ('system', 'Notificación del sistema')], max_length=50, verbose_name='Tipo'),
        ),
    ]
