# Generated by Django 5.2.7 on 2026-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_application', 'Nueva postulación recibida'), ('payment_verified', 'Pago verificado'), ('payment_rejected', 'Pago rechazado'), ('invoice_created', 'Orden de facturación creada'), ('invoice_completed', 'Facturación completada'), ('job_expiring_soon', 'Anuncio próximo a vencer'), ('job_expired', 'Anuncio vencido'), ('application_sent', 'Postulación enviada'), ('application_reviewing', 'Postulación en revisión'), ('application_shortlisted', 'Pre-seleccionado'), ('application_interviewed', 'Invitado a entrevista'), ('application_accepted', 'Postulación aceptada'), ('application_rejected', 'Postulación rechazada'), ('saved_job_closed', 'Trabajo guardado cerrado'), ('blocked_attempt', 'Intento de postulación bloqueado'), ('password_changed', 'Contraseña cambiada'), ('profile_updated', 'Perfil actualizado'), ('system', 'Notificación del sistema')], max_length=50, verbose_name='Tipo'),
        ),
    ]
