# Generated by Django 5.2.7 on 2025-11-26 23:43

from django.db import migrations


def populate_plans(apps, schema_editor):
    """Crear los 3 planes iniciales"""
    Plan = apps.get_model('G_Jobs.plans', 'Plan')

    # Plan Escencial
    Plan.objects.create(
        name='escencial',
        label='Escencial (35 Bs)',
        description='Plan básico para publicar anuncios',
        price=35.00,
        currency='Bs',
        duration_days=15,
        features={
            'maxAnnouncements': 1,
            'maxEditions': 999,  # Sin límite de ediciones
            'applicationForm': 'standard',
            'featured': False
        },
        is_active=True,
        order=1
    )

    # Plan Púrpura
    Plan.objects.create(
        name='purpura',
        label='Púrpura (79 Bs)',
        description='Plan intermedio con más visibilidad',
        price=79.00,
        currency='Bs',
        duration_days=30,
        features={
            'maxAnnouncements': 1,
            'maxEditions': 999,  # Sin límite de ediciones
            'applicationForm': 'custom',
            'featured': True,
            'highlightedResults': True
        },
        is_active=True,
        order=2
    )

    # Plan Impulso Pro
    Plan.objects.create(
        name='impulso',
        label='Impulso Pro (169 Bs)',
        description='Plan profesional con máximas características',
        price=169.00,
        currency='Bs',
        duration_days=30,
        features={
            'maxAnnouncements': 3,
            'maxEditions': 999,  # Sin límite de ediciones
            'applicationForm': 'custom',
            'featured': True,
            'highlightedResults': True,
            'premiumBadge': True,
            'socialMediaShare': True
        },
        is_active=True,
        order=3
    )

    print('[OK] 3 planes iniciales creados exitosamente')


def reverse_populate(apps, schema_editor):
    """Eliminar los planes (reversible)"""
    Plan = apps.get_model('G_Jobs.plans', 'Plan')
    Plan.objects.filter(name__in=['escencial', 'purpura', 'impulso']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.plans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_plans, reverse_populate),
    ]
