# Generated by Django 5.2.7 on 2025-11-27 00:31

from django.db import migrations


def populate_plan_fields(apps, schema_editor):
    """Migrar datos de JSON a campos separados"""
    Plan = apps.get_model('G_Jobs.plans', 'Plan')

    for plan in Plan.objects.all():
        features = plan.features if isinstance(plan.features, dict) else {}

        # Extraer valores de JSON y mapear a campos
        plan.max_announcements = features.get('maxAnnouncements', 1)
        plan.is_featured = features.get('featured', False)
        plan.has_highlighted_results = features.get('highlightedResults', False)

        plan.save()

    print('[OK] Campos de planes poblados desde JSON')


def reverse_populate(apps, schema_editor):
    """Reverse - resetear campos a valores por defecto"""
    Plan = apps.get_model('G_Jobs.plans', 'Plan')
    Plan.objects.all().update(
        max_announcements=1,
        is_featured=False,
        has_highlighted_results=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.plans', '0003_plan_application_form_plan_has_highlighted_results_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_plan_fields, reverse_populate),
    ]
