# Generated by Django 5.2.7 on 2025-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Jobs.plans', '0005_remove_unnecessary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='announcement_substitutions',
            field=models.IntegerField(default=0, help_text='Número de sustituciones de aviso permitidas (0 = No incluido)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='facebook_posts',
            field=models.IntegerField(default=1, help_text='Posts en Facebook/Instagram permitidos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='featured_days',
            field=models.IntegerField(default=0, help_text='Días que permanecerá destacado (0 = sin duración)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='linkedin_posts',
            field=models.IntegerField(default=0, help_text='Posts en LinkedIn permitidos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiktok_posts',
            field=models.IntegerField(default=0, help_text='Posts en TikTok permitidos'),
        ),
    ]
