# Generated by Django 5.2.7 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_add_social_and_featured_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Nombre único del plan (ej: escencial, purpura, impulso)', max_length=50, unique=True),
        ),
    ]
