# Generated by Django 5.2.7 on 2025-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_label',
            field=models.CharField(blank=True, default='', help_text="Texto del badge (ej: 'Básico', 'Popular', 'Premium'). Dejar vacío si no deseas mostrar badge.", max_length=50),
        ),
    ]
