# Generated by Django 5.2.7 on 2025-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado'), ('soft_delete', 'Eliminado'), ('restore', 'Restaurado'), ('pause', 'Pausado'), ('activate', 'Activado'), ('close', 'Cerrado'), ('verify_payment', 'Pago Verificado'), ('reject_payment', 'Pago Rechazado'), ('duplicate', 'Duplicado'), ('view', 'Visualizado'), ('export', 'Exportado'), ('block_attempt', 'Intento de Aplicación Bloqueado'), ('other', 'Otra Acción')], max_length=20, verbose_name='Acción'),
        ),
    ]
