# Generated by Django 5.2.7 on 2025-12-17 12:36

import G_Jobs.applicants.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0030_alter_blockeduser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_type', models.CharField(choices=[('created', 'CV Creado en Plataforma'), ('uploaded', 'CV Subido (PDF/DOC)')], max_length=20, verbose_name='Tipo de CV')),
                ('name', models.CharField(help_text='Ej: CV para Desarrollo Web, CV General', max_length=200, verbose_name='Nombre del CV')),
                ('cv_data', models.JSONField(blank=True, help_text='Datos estructurados del CV en formato Harvard', null=True, verbose_name='Datos del CV')),
                ('file', models.FileField(blank=True, null=True, upload_to='applicant_cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), G_Jobs.applicants.models.validate_file_size], verbose_name='Archivo CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'CV de Postulante',
                'verbose_name_plural': 'CVs de Postulantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='Perfil de LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, max_length=500, verbose_name='Portafolio/Sitio Web')),
                ('desired_job_categories', models.JSONField(blank=True, default=list, verbose_name='Categorías de trabajo deseadas')),
                ('desired_cities', models.JSONField(blank=True, default=list, verbose_name='Ciudades preferidas')),
                ('desired_modality', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('any', 'Cualquiera')], default='any', max_length=20, verbose_name='Modalidad preferida')),
                ('total_applications', models.IntegerField(default=0, verbose_name='Total de postulaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Postulante',
                'verbose_name_plural': 'Perfiles de Postulantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de Presentación')),
                ('status', models.CharField(choices=[('submitted', 'Enviada'), ('reviewing', 'En Revisión'), ('shortlisted', 'Pre-seleccionado'), ('interviewed', 'Entrevistado'), ('rejected', 'Rechazado'), ('accepted', 'Aceptado'), ('withdrawn', 'Retirada')], default='submitted', max_length=20, verbose_name='Estado')),
                ('screening_answers', models.JSONField(blank=True, default=dict, verbose_name='Respuestas a preguntas de filtrado')),
                ('employer_notes', models.TextField(blank=True, verbose_name='Notas del empleador')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('viewed_by_employer', models.BooleanField(default=False, verbose_name='Vista por empleador')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de visualización')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Postulante')),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applicants.applicantcv', verbose_name='CV Utilizado')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_applications', to='jobs.job', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de guardado')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job', verbose_name='Trabajo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Trabajo Guardado',
                'verbose_name_plural': 'Trabajos Guardados',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicantcv',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cv_data__isnull', False), ('cv_type', 'created')), models.Q(('cv_type', 'uploaded'), ('file__isnull', False)), _connector='OR'), name='cv_data_or_file_required'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='applicants__job_id_18298b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='applicants__applica_0ca45a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['-applied_at'], name='applicants__applied_0c0990_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
