# Generated by Django 5.2.7 on 2025-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Puntuación de 1 a 5 estrellas', null=True, verbose_name='Calificación'),
        ),
    ]
