# Generated by Django 5.2.7 on 2025-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_add_rating_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
