# Generated by Django 5.2.7 on 2025-12-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicantprofile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp (ej: 59176543210) - Se usa para botón de contacto directo en dashboard', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
