# Generated by Django 5.2.7 on 2026-01-02 19:52

import G_Jobs.applicants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicantprofile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='attached_cv_file',
            field=models.FileField(blank=True, help_text='CV enviado directamente con esta postulación', null=True, upload_to='application_cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), G_Jobs.applicants.models.validate_file_size], verbose_name='CV Adjunto'),
        ),
    ]
