# Generated by Django 5.2.7 on 2026-01-05 12:45

import G_Jobs.applicants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_jobapplication_attached_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantcv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=G_Jobs.applicants.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), G_Jobs.applicants.models.validate_file_size], verbose_name='Archivo CV'),
        ),
    ]
