# Generated by Django 5.2.7 on 2026-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicantcv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='ci',
            field=models.CharField(blank=True, help_text='Número de CI o documento de identidad', max_length=20, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='driver_license_category',
            field=models.CharField(blank=True, help_text='Ej: A, B, C, Profesional', max_length=50, verbose_name='Categoría de licencia'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='has_criminal_record',
            field=models.BooleanField(default=False, verbose_name='¿Tiene antecedentes penales?'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='has_driver_license',
            field=models.BooleanField(default=False, verbose_name='¿Tiene licencia de conducir?'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Boliviana', max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
