# Generated by Django 5.2.7 on 2025-12-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_plan_applicant_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='plan',
            name='visibility_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('destacado', 'Destacado'), ('patrocinado', 'Patrocinado')], default='normal', help_text='Tipo de visibilidad del anuncio en la plataforma', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='featured_days',
            field=models.IntegerField(default=0, help_text='Días que permanecerá destacado/patrocinado (0 = sin duración específica)'),
        ),
    ]
