# Generated by Django 5.2.7 on 2025-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('new_users', models.IntegerField(default=0, verbose_name='Nuevos Usuarios')),
                ('new_companies', models.IntegerField(default=0, verbose_name='Nuevas Empresas')),
                ('new_applicants', models.IntegerField(default=0, verbose_name='Nuevos Postulantes')),
                ('total_active_users', models.IntegerField(default=0, verbose_name='Usuarios Activos Totales')),
                ('new_jobs', models.IntegerField(default=0, verbose_name='Trabajos Publicados')),
                ('active_jobs', models.IntegerField(default=0, verbose_name='Trabajos Activos')),
                ('closed_jobs', models.IntegerField(default=0, verbose_name='Trabajos Cerrados')),
                ('total_views', models.IntegerField(default=0, verbose_name='Vistas Totales')),
                ('plans_sold', models.IntegerField(default=0, verbose_name='Planes Vendidos')),
                ('plan_estandar_count', models.IntegerField(default=0, verbose_name='Plan Estándar')),
                ('plan_purpura_count', models.IntegerField(default=0, verbose_name='Plan Púrpura')),
                ('plan_impulso_count', models.IntegerField(default=0, verbose_name='Plan Impulso')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Totales (Bs)')),
                ('revenue_estandar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Estándar')),
                ('revenue_purpura', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Púrpura')),
                ('revenue_impulso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Impulso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-date'],
            },
        ),
    ]
