# jobs/constants.py
"""
Constantes para el módulo de trabajos
"""

JOB_CATEGORIES = [
    'Administración y Gestión',
    'Agronomía y Veterinaria',
    'Atención al Cliente',
    'Banca y Finanzas',
    'Comercial y Ventas',
    'Comunicaciones y Medios',
    'Construcción e Inmobiliario',
    'Consultoría y Asesoría',
    'Diseño y Artes Gráficas',
    'Educación e Institutos',
    'Energía y Minería',
    'Estrategia y Dirección',
    'Fabricación y Manufactura',
    'Farmacia y Cosmética',
    'Finanzas y Contabilidad',
    'Fotografía y Video',
    'Gastronomía y Alimentos',
    'Gestión Administrativa',
    'Gestión de Proyectos',
    'Gestión Humana y Reclutamiento',
    'Gestión Logística y Almacenes',
    'Ingeniería Civil',
    'Ingeniería Eléctrica',
    'Ingeniería Industrial',
    'Ingeniería Mecánica',
    'Ingeniería de Sistemas',
    'Ingeniería Informática',
    'Ingeniería Química',
    'Investigación y Análisis',
    'Justicia y Legal',
    'Logística y Transporte',
    'Manufactura y Producción',
    'Marketing y Publicidad',
    'Mecánica y Reparaciones',
    'Medios Audiovisuales',
    'Obrería y Oficios',
    'Producción Audiovisual',
    'Producción Cinematográfica',
    'Programación y Desarrollo',
    'Psicología y Recursos Humanos',
    'Publicaciones Digitales',
    'Recursos Naturales',
    'Relaciones Públicas',
    'Reparación y Mantenimiento',
    'Retail y Comercio',
    'Salud y Medicina',
    'Seguridad Ocupacional',
    'Seguridad y Vigilancia',
    'Servicios',
    'Servicios Bancarios',
    'Servicios Financieros',
    'Soluciones de Software',
    'Sostenibilidad y Medio Ambiente',
    'Telecomunicaciones',
    'Tecnología e Informática',
    'Tecnología y Digital',
    'Telecomunicaciones y Redes',
    'Telemarketing',
    'Tiendas Departamentales',
    'Trabajo Social',
    'Trading y Bolsa',
    'Transporte y Logística',
    'Turismo y Hostelería',
    'UX/UI y Diseño Digital',
    'Ventas',
    'Veterinaria',
    'Vivienda e Inmobiliario',
    'Otra categoría'
]
