# Generated by Django 5.2.7 on 2025-12-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_actions', models.IntegerField(default=0, verbose_name='Total de Acciones')),
                ('total_creates', models.IntegerField(default=0, verbose_name='Creaciones')),
                ('total_updates', models.IntegerField(default=0, verbose_name='Actualizaciones')),
                ('total_deletes', models.IntegerField(default=0, verbose_name='Eliminaciones')),
                ('unique_users', models.IntegerField(default=0, verbose_name='Usuarios Únicos')),
                ('critical_events', models.IntegerField(default=0, verbose_name='Eventos Críticos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
            ],
            options={
                'verbose_name': 'Resumen de Auditoría',
                'verbose_name_plural': 'Resúmenes de Auditoría',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email guardado para referencia histórica (en caso de que el usuario se elimine)', max_length=255, verbose_name='Email del Usuario')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rol del Usuario')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(help_text='Nombre/título del objeto para referencia rápida', max_length=500, verbose_name='Representación del Objeto')),
                ('action', models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado'), ('soft_delete', 'Eliminado (Lógico)'), ('restore', 'Restaurado'), ('pause', 'Pausado'), ('activate', 'Activado'), ('close', 'Cerrado'), ('verify_payment', 'Pago Verificado'), ('reject_payment', 'Pago Rechazado'), ('duplicate', 'Duplicado'), ('view', 'Visualizado'), ('export', 'Exportado'), ('other', 'Otra Acción')], max_length=20, verbose_name='Acción')),
                ('action_description', models.TextField(blank=True, help_text='Descripción detallada de lo que se hizo', verbose_name='Descripción de la Acción')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Diccionario con los valores antes/después de cada campo modificado', verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y sistema operativo del usuario', verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=255, verbose_name='Session Key')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='info', max_length=10, verbose_name='Severidad')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['user_email'], name='audit_audit_user_em_fa26db_idx')],
            },
        ),
    ]
