# Generated by Django 5.2.7 on 2025-12-15 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Comportamiento inapropiado'), ('unqualified', 'No calificado repetidamente'), ('other', 'Otra razón')], max_length=50, verbose_name='Razón')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloqueado el')),
                ('blocked_user', models.ForeignKey(limit_choices_to={'role': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_companies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario bloqueado')),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_blocked_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Usuario Bloqueado',
                'verbose_name_plural': 'Usuarios Bloqueados',
                'db_table': 'jobs_blockeduser',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['company', '-blocked_at'], name='jobs_blocke_company_f96a2e_idx'), models.Index(fields=['blocked_user'], name='jobs_blocke_blocked_6c5128_idx')],
                'unique_together': {('company', 'blocked_user')},
            },
        ),
    ]
