# Generated by Django 5.2.7 on 2025-11-26 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_municipality_job_softskills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paymentVerificationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='job',
            name='paymentVerificationNotes',
            field=models.TextField(blank=True, verbose_name='Notas de verificación'),
        ),
        migrations.AddField(
            model_name='job',
            name='paymentVerified',
            field=models.BooleanField(default=False, verbose_name='Pago verificado'),
        ),
        migrations.AddField(
            model_name='job',
            name='paymentVerifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='job',
            name='proofOfPayment',
            field=models.ImageField(null=True, upload_to='payment_proofs/', verbose_name='Comprobante de pago'),
        ),
    ]
