# Generated by Django 5.2.7 on 2025-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_paymentverificationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
