# Generated by Django 5.2.7 on 2025-12-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_job_education_remove_job_experience_and_more'),
        ('plans', '0008_plan_badge_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('UNQUALIFIED', 'No Calificado'), ('OTHER', 'Otro')], max_length=20, verbose_name='Razón del Bloqueo')),
                ('reason_notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Bloqueo')),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Dejar en blanco para bloqueo permanente', null=True, verbose_name='Bloqueado Hasta')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='¿Es Permanente?')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_companies', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Bloqueado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='Empresa que Bloquea')),
            ],
            options={
                'verbose_name': 'Usuario Bloqueado',
                'verbose_name_plural': 'Usuarios Bloqueados',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['company', '-blocked_at'], name='jobs_blocke_company_f96a2e_idx'), models.Index(fields=['blocked_user'], name='jobs_blocke_blocked_6c5128_idx')],
                'unique_together': {('company', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Factura')),
                ('nit', models.CharField(help_text='Número de Identificación Tributaria', max_length=20, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('ci', models.CharField(help_text='Cédula de Identidad del representante', max_length=20, verbose_name='CI')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprobante de Pago')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('electronic_invoice_sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío de Factura Electrónica')),
                ('electronic_invoice_email', models.EmailField(blank=True, max_length=254, verbose_name='Email para Factura Electrónica')),
                ('electronic_invoice_whatsapp', models.CharField(blank=True, help_text='Número de teléfono para envío por WhatsApp', max_length=20, verbose_name='WhatsApp para Factura Electrónica')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado'), ('INVOICE_SENT', 'Factura Enviada'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('company_data', models.JSONField(blank=True, default=dict, help_text='Datos del SummaryCard al momento de la compra', verbose_name='Datos de la Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_orders', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orden de Plan',
                'verbose_name_plural': 'Órdenes de Planes',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['user', '-order_date'], name='jobs_planor_user_id_c84a65_idx'), models.Index(fields=['status'], name='jobs_planor_status_5aa25d_idx'), models.Index(fields=['invoice_number'], name='jobs_planor_invoice_75b927_idx')],
            },
        ),
    ]
