# Generated by Django 5.2.7 on 2025-12-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_blockeduser_planorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobauditlog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='jobs.job', verbose_name='Trabajo'),
        ),
    ]
