# Generated by Django 5.2.7 on 2025-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_city_contracttype_jobcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='selectedPlan',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('purpura', 'Púrpura'), ('impulso', 'Impulso Pro')], default='estandar', max_length=50, verbose_name='Plan seleccionado'),
        ),
        migrations.AlterField(
            model_name='planorder',
            name='selected_plan',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('purpura', 'Púrpura'), ('impulso', 'Impulso Pro')], default='estandar', max_length=50, verbose_name='Plan seleccionado'),
        ),
    ]
