# Generated by Django 5.2.7 on 2025-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_alter_planorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicationType',
            field=models.CharField(choices=[('internal', 'Interna (en Guías Púrpuras)'), ('external', 'Externa (URL propia)')], default='internal', max_length=20, verbose_name='Tipo de aplicación'),
        ),
    ]
