# Generated by Django 5.2.7 on 2025-11-20 14:31

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=profiles.models.generate_profile_id, max_length=8, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.CharField(default=profiles.models.generate_profile_id, max_length=8, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=200, verbose_name='Nombre de Empresa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo de Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Empresa')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('category', models.CharField(choices=[('jobs', 'Empleador - Trabajos'), ('restaurant', 'Restaurante - Gastronomía'), ('business', 'Negocio'), ('professional', 'Profesional'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Categoría')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='profiles.userprofile', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresas',
                'ordering': ['-createdAt'],
            },
        ),
    ]
