# Generated by Django 5.2.7 on 2025-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/', verbose_name='Banner de Empresa'),
        ),
    ]
