# Generated by Django 5.2.7 on 2025-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_companyprofile_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='legalName',
            field=models.CharField(blank=True, max_length=300, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='nit',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIT (Número de Identificación Tributaria)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seprecCode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código SEPREC (Matrícula de Comercio)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verificationNotes',
            field=models.TextField(blank=True, verbose_name='Notas de Verificación (solo admin)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verificationRequestedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solicitud de Verificación'),
        ),
    ]
