# Generated by Django 5.2.7 on 2026-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_company_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ci',
            field=models.CharField(blank=True, help_text='Número de CI o documento de identidad', max_length=20, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driverLicenseCategory',
            field=models.CharField(blank=True, help_text='Ej: A, B, C, Profesional', max_length=50, verbose_name='Categoría de licencia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hasCriminalRecord',
            field=models.BooleanField(default=False, verbose_name='¿Tiene antecedentes penales?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hasDriverLicense',
            field=models.BooleanField(default=False, verbose_name='¿Tiene licencia de conducir?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Boliviana', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='category',
            field=models.CharField(choices=[('jobs', 'Empleador - Trabajos')], default='jobs', max_length=50, verbose_name='Categoría'),
        ),
    ]
