# Generated by Django 5.2.7 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la ciudad')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('region', models.CharField(blank=True, choices=[('altiplano', 'Altiplano'), ('valles', 'Valles'), ('llanos', 'Llanos')], max_length=50, verbose_name='Región')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'jobs_city',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='jobs_city_slug_32b22c_idx'), models.Index(fields=['is_active', 'order'], name='jobs_city_is_acti_75d27e_idx'), models.Index(fields=['region'], name='jobs_city_region_6d31a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de contrato')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'db_table': 'jobs_contracttype',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='jobs_contra_slug_b0063c_idx'), models.Index(fields=['is_active', 'order'], name='jobs_contra_is_acti_0f056e_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generado)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono (Material Icons)', max_length=50, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Trabajo',
                'verbose_name_plural': 'Categorías de Trabajo',
                'db_table': 'jobs_jobcategory',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='jobs_jobcat_slug_3b5636_idx'), models.Index(fields=['is_active', 'order'], name='jobs_jobcat_is_acti_d56492_idx')],
            },
        ),
    ]
